apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: bgremover-devsecops:apps/Deployment:default/background-remover-python-app
  labels:
    app: background-remover-python-app
  name: background-remover-python-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: background-remover-python-app
  template:
    metadata:
      labels:
        app: background-remover-python-app
    spec:
      containers:
        - image: rineeth05/bg-remover-python-app:latest
          name: bg-remover-python-app:latest
          ports:
            - containerPort: 5100
