apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-remover-python-app
  namespace: default
  labels:
    app: background-remover-python-app
  annotations:
    argocd.argoproj.io/tracking-id: bgremover-devsecops:apps/Deployment:default/background-remover-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: background-remover-python-app
  template:
    metadata:
      labels:
        app: background-remover-python-app
    spec:
      containers:
        - name: background-remover-python-app
          image: rineeth05/background-remover-python-app:latest
          ports:
            - containerPort: 5100
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 5100
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5100
            initialDelaySeconds: 5
            periodSeconds: 5
