apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-remover-python-app
  labels:
    app: background-remover-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: background-remover-python-app
  template:
    metadata:
      labels:
        app: background-remover-python-app
    spec:
      containers:
        - name: bg-remover-python-app:latest
          image: rineeth05/bg-remover-python-app:latest
          ports:
            - containerPort: 5100
