apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-remover-python-app
  namespace: default
  labels:
    app: background-remover-python-app
  annotations:
    argocd.argoproj.io/tracking-id: bgremover-devsecops:apps/Deployment:default/background-remover-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: background-remover-python-app
  template:
    metadata:
      labels:
        app: background-remover-python-app
    spec:
      containers:
        - name: bg-remover-python-app
          image: rineeth05/bg-remover-python-app:latest
          ports:
            - containerPort: 5100
